version: "3"

services:

  application:
    image: "sonyamoonglade/ci_cd_app"
    build:
      context: "../."
    env_file: ".env"
    ports:
      - "5000:5000"
    networks:
      - inet

  db:
    image: "postgres"
    container_name: db
    build:
      context: "../."
    env_file: ".env"
    environment:
      - POSTGRES_PASSWORD=${DB_PWD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    restart: on-failure
    depends_on:
      - stage-migrations
    networks:
      - inet
  
  stage-migrations:
    image: "migrate/migrate"
    build:
      context: "../."
    volumes:
      - ./migrations:/migrations
    env_file: ".env"
    command:
     ["migrate", "-path", "./migrations", "-database", "$(echo ${DATABASE_URL})", "-verbose", "up"]
    networks:
      - inet
    restart: on-failure


  
networks:
  inet:
    driver: bridge

